= Dapr Client for Ruby
:ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Overview

This library provides a Ruby client for the Dapr runtime. It is a work in progress and is not yet ready for production use.

== Installation

Install the gem and add to the application's Gemfile by executing:

    $ bundle add dapr-client

If bundler is not being used to manage dependencies, install the gem by executing:

    $ gem install dapr-client

== Usage

This library is a WIP and will be documented as the interface is finalized.

== Development

After checking out the repo, run `bin/setup` to install dependencies. Then, run `rake spec` to run the tests. You can also run `bin/console` for an interactive prompt that will allow you to experiment.

To install this gem onto your local machine, run `bundle exec rake install`. To release a new version, update the version number in `version.rb`, and then run `bundle exec rake release`, which will create a git tag for the version, push git commits and the created tag, and push the `.gem` file to https://rubygems.org[rubygems.org].

== Contributing

Bug reports and pull requests are welcome on GitHub at https://github.com/rubyists/dapr.
