= Dapr Client for Ruby
:ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:dapr-building-block: https://docs.dapr.io/concepts/building-blocks-concept/[Dapr Building Block]

== Overview

This library provides a Ruby client for the Dapr runtime. It is a work in progress and is not yet ready for production use.

Documentation will be added as the library matures.

== Installation

Install the gem and add to the application's Gemfile by executing:

    $ bundle add dapr --require dapr/client

If bundler is not being used to manage dependencies, install the gem by executing:

    $ gem install dapr

== Usage

Dapr being such a kitchen sink, the client exposes each dapr building block as either a
client or a service, depending on whether it uses the AppCallback runtime (Service) or
the Dapr API (Client). The clients art thin wrappers around the Dapr API, while the service
is a more opinionated and higher-level abstraction.

Each {dapr-building-block} is exposed as a class under the `Rubyists::Dapr::Client` or
`Rubyists::Dapr::Service` namespace.

=== Publish a message

[source,ruby]
----
require 'dapr/client/publisher'
ENV['DAPR_GRPC_PORT'] = '3500' <1>
publisher = Rubyists::Dapr::Client::Publisher.new('pubsub-name') <2>
publisher.publish('topic-name', { message: 'Hello, Dapr!', from: 'Ruby' })
----
<1> Set the Dapr gRPC port to the Dapr runtime port. (This is automatically set in kubernetes environments)
<2> Create a new publisher for the `pubsub-name` pubsub component. This component must be defined in the Dapr runtime.
<3> Publish a message to the `topic-name` topic.

=== Subscribe to topics

Subscriptions in Dapr work a little different than you may be used to. Instead of subscribing to a topic
then looping through consumed messages, you define a fully-fledged service that Dapr will
send each message to in the topic(s) that you specify. This unique appreach allows you to
focus on the business logic of your service, rather than the plumbing of message consumption.

[source,ruby]
----
require 'dapr/service/subscriber'
handler = ->(event) { puts "Got event: #{event}" } <1>
pubsub_name = 'pubsub' <2>
topics = 'TOPIC-A' <3>
sub = Rubyists::Dapr::Service::Subscriber.new(pubsub_name:, topics:, handler:) <4>
sub.start! <5>
----
<1> Define a handler that will be called for each message received. `event` will be a `CloudEvents::Event` instance.
+
NOTE: The handler can be anything that responds to `#call`, such as a lambda, proc, or instance. Sky's the limit! (Dependency injection, anyone?)
+
<2> The name of the Dapr pubsub component this subscriber will utilize.
<3> The name of the topic(s) to subscribe to.
+
TIP: Multiple topics can be subscribed to simultaneously by passing an array of topic names to the `topics` argument.
+
<4> Create a new subscriber for the `pubsub` pubsub component, subscribing to the `TOPIC-A` topic.
<5> Start the subscriber. This will block the current thread and call the handler for each message received.

== Development

After checking out the repo, run `bin/setup` to install dependencies. Then, run `rake spec` to run the tests. You can also run `bin/console` for an interactive prompt that will allow you to experiment.

To install this gem onto your local machine, run `bundle exec rake install`. To release a new version, update the version number in `version.rb`, and then run `bundle exec rake release`, which will create a git tag for the version, push git commits and the created tag, and push the `.gem` file to https://rubygems.org[rubygems.org].

== Contributing

Bug reports and pull requests are welcome on GitHub at https://github.com/rubyists/dapr.
