---
name: Publish Ruby Gem
on:  # yamllint disable-line rule:truthy
  workflow_call:
  workflow_dispatch:
jobs:
  publish_github:
    name: Publish the gem to github
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v4
      -
        name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.1
          bundler-cache: true
      -
        name: Publish to github
        env:
          TRACE: ${{ secrets.ACTIONS_STEP_DEBUG || 'false' }}
          GEM_TOKEN: ${{ secrets.RELEASE_PLEASE_TOKEN }}
        run: |
          TRACE="$TRACE" GEM_TOKEN=$GEM_TOKEN ./ci/publish-gem.sh github
        shell: bash

  publish_rubygems:
    name: Publish to rubygems
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v4
      -
        name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.1
          bundler-cache: true
      -
        name: Publish to rubygems
        env:
          GEM_TOKEN: ${{ secrets.RUBYGEMS_TOKEN }}
          TRACE: ${{ secrets.ACTIONS_STEP_DEBUG || 'false' }}
        run: |
          TRACE="$TRACE" GEM_TOKEN="$GEM_TOKEN" ./ci/publish-gem.sh rubygems
        shell: bash
