---
name: Publish Ruby Gem
on:  # yamllint disable-line rule:truthy
  workflow_call:
  workflow_dispatch:
jobs:
  shared_config:
    name: Shared configuration for jobs
    env:
      GEM_NAME: dapr
      GEM_VERSION: ${{ github.event.inputs.gem_version }}

    outputs:
      gem_name: ${{ steps.configure.outputs.gem_name }}
      gem_version: ${{ steps.configure.outputs.gem_version }}

    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v4
      -
        id: configure
        name: Configure gem jobs
        #  Create outputs for all the env vars
        run: |
          release_version=$(<.version.txt)
          printf '::set-output name=gem_name::%s\n' "$GEM_NAME"
          printf '::set-output name=gem_version::%s\n' "$release_version"
        shell: bash

  publish_github:
    name: Publish the gem to github
    needs: shared_config
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v4
      -
        name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.1
          bundler-cache: true
      -
        name: Publish to github
        env:
          GEM_NAME: ${{ needs.shared_config.outputs.gem_name }}
          GEM_VERSION: ${{ needs.shared_config.outputs.gem_version }}
        # yamllint disable rule:line-length
        run: |
          # If the workflos does not provide a version, use the one in the .version.txt file
          [ "$GEM_VERSION" = "0.0.0" ] && version=$(<.version.txt)
          gem="$(printf '%s-%s.gem' "$GEM_NAME" "$version")"
          mkdir -p ~/.gem
          token=${{ secrets.GITHUB_TOKEN }}
          printf '%s\n:github: Bearer %s\n' '---' "$token" > ~/.gem/credentials
          chmod 600 ~/.gem/credentials
          printf 'Publishing %s to github\n' "$gem"
          sed -i -e "s|https://rubygems.org|https://rubygems.pkg.github.com/$GIT_ORG|" $GEM_NAME.gemspec
          bundle exec gem build
          bundle exec gem push -k github --host https://rubygems.pkg.github.com/$GIT_ORG "$gem"
        # yamllint enable rule:line-length
        shell: bash

  publish_rubygems:
    name: Publish to rubygems
    needs: shared_config
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v4
      -
        name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.1
          bundler-cache: true
      -
        name: Publish to rubygems
        env:
          GEM_NAME: ${{ needs.shared_config.outputs.gem_name }}
          GEM_VERSION: ${{ needs.shared_config.outputs.gem_version }}
          RUBYGEMS_TOKEN: ${{ secrets.RUBYGEMS_TOKEN }}
        # yamllint disable rule:line-length
        run: |
          if [ -z "$RUBYGEMS_TOKEN" ]
          then
            printf 'No rubygems token provided, cannot publish\n'
            exit 1
          fi
          # If the workflow does not provide a version, use the one in the .version.txt file
          gem="$(printf '%s-%s.gem' "$GEM_NAME" "$version")"
          mkdir -p ~/.gem
          printf '%s\n:rubygems: %s\n' '---' "$RUBYGEMS_TOKEN" > ~/.gem/credentials
          chmod 600 ~/.gem/credentials
          printf 'Publishing %s to rubygems\n' "$gem"
          bundle exec gem build
          bundle exec gem push -k rubygems --host https://rubygems.org "$gem"
        # yamllint enable rule:line-length
        shell: bash
