---
name: Publish Ruby Gem
on:  # yamllint disable-line rule:truthy
  workflow_call:
  workflow_dispatch:
jobs:
  shared_config:
    name: Shared configuration for jobs
    env:
      GEM_NAME: dapr
      GEM_VERSION: ${{ github.event.inputs.gem_version }}

    outputs:
      gem_name: ${{ steps.configure.outputs.gem_name }}
      gem_version: ${{ steps.configure.outputs.gem_version }}

    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v4
      -
        id: configure
        name: Configure gem jobs
        #  Create outputs for all the env vars
        run: ./ci/configure-gem-jobs.sh

  publish_github:
    name: Publish the gem to github
    needs: shared_config
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v4
      -
        name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.1
          bundler-cache: true
      -
        name: Publish to github
        env:
          GEM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TRACE: ${{ secrets.ACTIONS_STEP_DEBUG || 'false' }}
        run: |
          TRACE="$TRACE" GEM_TOKEN="$GEM_TOKEN" ./ci/publish-gem.sh github
        shell: bash

  publish_rubygems:
    name: Publish to rubygems
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v4
      -
        name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.1
          bundler-cache: true
      -
        name: Publish to rubygems
        env:
          GEM_TOKEN: ${{ secrets.RUBYGEMS_TOKEN }}
          TRACE: ${{ secrets.ACTIONS_STEP_DEBUG || 'false' }}
        run: |
          TRACE="$TRACE" GEM_TOKEN="$GEM_TOKEN" ./ci/publish-gem.sh rubyists
        shell: bash
