---
name: Ruby PR Validation (tests and linting)

on:  # yamllint disable-line rule:truthy
  pull_request:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.3.0'
          - '3.3.1'

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run the default rake task
        run: bundle exec rake
