---
name: Ruby Validations (tests and linting)

on:  # yamllint disable-line rule:truthy
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.3.0'
          - '3.3.1'
          - '3.3.2'

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run the default rake task
        run: bundle exec rake
