---
name: Release

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      force:
        description: 'Force publish the gem'
        required: false
        type: boolean

jobs:
  validate_ruby:
    if: ${{ ! github.event.inputs.force }}
    name: Ruby Tests
    uses: ./.github/workflows/main.yml

  validate_codeql:
    if: ${{ ! github.event.inputs.force }}
    name: CodeQL Analysis
    uses: ./.github/workflows/main.yml

  release:
    needs: [validate_ruby, validate_codeql]
    name: Create a release
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      -
        uses: actions/checkout@v4
        id: git-checkout
        with:
          fetch-tags: true
      -
        uses: googleapis/release-please-action@v4
        id: release
        with:
          config-file: .release-please-config.json
          manifest-file: .release-please-manifest.json
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
      -
        if: >
          steps.release.outputs.release_created || github.event.inputs.force
        name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.1
          bundler-cache: true

  gem:
    needs: release
    name: Publish the gem
    uses: ./.github/workflows/gem.yaml
